### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by rhysong** [karlie-tr/dsci-310-group-03#146]
### Conflict of interest

- [x] As the reviewer I confirm that I have no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).

### General checks

- [x] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

### Documentation

- [x] **Installation instructions:** Is there a clearly stated list of dependencies? 
- [x] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [x] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Code quality
- [x] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [x] **Style guidelides:** Does the code adhere to well known language style guides?
- [x] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?

### Reproducibility
 
- [x] **Data:** Is the raw data archived somewhere? Is it accessible?
- [x] **Computational methods:** Is all the source code required for the data analysis available?
- [x] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [x] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?

### Analysis report

- [x] **Authors:** Does the report include a list of authors with their affiliations?
- [x] **What is the question:** Do the authors clearly state the research question being asked?
- [x] **Importance:** Do the authors clearly state the importance for this research question?
- [x] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [x] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [x] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [x] **Conclusions:** Are the conclusions presented by the authors correct? 
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Writing quality:** Is the writing of good quality, concise, engaging? 

### Review Comments: 

Overall great work! I have kept my feedback only towards the overall document generation and workflow. Here are some feedback
1) Running Analysis Step 2: I believe it is not necessary to specify a docker pull as docker build will check if you have the specified image and if it does not exist it will automatically pull from docker-hub.
2)  Bookdown package missing: Make all execution failed due to missing the bookdown package within the docker image.
3) Code typo in line 150 of RMD file error line:
 knitr::include_graphics(here("results/final_classification_plot.png"))s
5) Unsure if figure 5.1 did not generate correctly or that the data only had exercise pain values of 0 and 1 ( I assume it is exertion pain in the source data) . Was this a boolean variable? If it was I think there is better ways of generating this visualization.  Perhaps a bar graph would be easier?
6) Figure 4.2 generation is squished should be split into two graphs instead of placed side by side.
7) Could split script files up more, some R scripts contained both visualization and modelling, it was a bit unclear the specific function each file had. Prehaps all modelling code could go into a selection+modelling script while 2 seperate scripts generated visualizations before modelling and after modelling. This would help keep the workflow cleaner.
8) Loved the code style! Very clean and intuitive!

#### Attribution

This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.

**Comment by karlie-tr** [comment]
TO DO:

- [ ] Update README: instructions
- [ ] Update bookdown package in docker
- [ ] Code typo in line 150 of RMD file error line:
```knitr::include_graphics(here("results/final_classification_plot.png"))s```
- [ ] Figure 5.1 visualization
- [ ] Script files into selection + modelling; figure generation
